# Generated by Django 5.2.3 on 2025-07-22 02:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "movie_id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        verbose_name="映画ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="タイトル")),
                (
                    "genres",
                    models.TextField(blank=True, null=True, verbose_name="ジャンル"),
                ),
                (
                    "director",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="監督"
                    ),
                ),
                (
                    "actors",
                    models.TextField(blank=True, null=True, verbose_name="俳優"),
                ),
                (
                    "release_year",
                    models.IntegerField(blank=True, null=True, verbose_name="公開年"),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="制作国"
                    ),
                ),
                (
                    "movie_poster_url",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="ポスター画像URL",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(blank=True, null=True, verbose_name="評価"),
                ),
                (
                    "impressions",
                    models.TextField(blank=True, null=True, verbose_name="感想"),
                ),
                ("watched_date", models.DateField(verbose_name="視聴日")),
                (
                    "watch_method",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="視聴方法"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "verbose_name": "映画",
                "verbose_name_plural": "映画",
                "db_table": "movies",
            },
        ),
    ]
