# Generated by Django 5.2.3 on 2025-07-23 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Movie",
        ),
    ]
