# Generated by Django 5.2.3 on 2025-07-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="タイトル")),
                (
                    "genres",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="ジャンル"
                    ),
                ),
                (
                    "director",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="監督"
                    ),
                ),
                (
                    "actors",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="俳優"
                    ),
                ),
                (
                    "release_year",
                    models.IntegerField(blank=True, null=True, verbose_name="公開年"),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="制作国"
                    ),
                ),
                (
                    "movie_poster_url",
                    models.URLField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="ポスターURL",
                    ),
                ),
                (
                    "rating",
                    models.FloatField(blank=True, null=True, verbose_name="評価"),
                ),
                (
                    "impressions",
                    models.TextField(blank=True, null=True, verbose_name="感想"),
                ),
                (
                    "watch_method",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="視聴方法"
                    ),
                ),
                (
                    "watched_date",
                    models.DateField(blank=True, null=True, verbose_name="視聴日"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "verbose_name": "映画",
                "db_table": "movies",
            },
        ),
    ]
