# Generated by Django 5.2.3 on 2025-07-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="movie_poster_url",
        ),
        migrations.AddField(
            model_name="movie",
            name="movie_poster",
            field=models.ImageField(
                blank=True, null=True, upload_to="posters/", verbose_name="ポスター画像"
            ),
        ),
    ]
