# Generated by Django 5.2.3 on 2025-07-23 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_remove_movie_movie_poster_url_movie_movie_poster"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="movie",
            table=None,
        ),
    ]
